---
argument_specs:
  main:
    short_description: Install a list of Helm charts.
    options:
      releases:
        type: list
        elements: dict
        required: true
        description: |
          List of dictionaries passed as arguments to kubernetes.core.helm.
          Arguments passed here will override  those in `helm_settings`.  For
          structure of the dictionary, see the documentation for
          kubernetes.core.helm ansible module.
        options:
          chart_ref:
            type: path
            required: true
          chart_version:
            type: str
          name:
            type: str
            required: true
          namespace:
            type: str
            required: true
          values:
            type: dict
          # Possibly general options
          create_namespace:
            type: bool
          chart_repo_url:
            type: str
          disable_hook:
            type: bool
          history_max:
            type: int
          purge:
            type: bool
          replace:
            type: bool
          skip_crds:
            type: bool
          wait:
            type: bool
            default: true
          wait_timeout:
            type: str
          atomic:
            type: bool
            default: true

      repositories:
        type: list
        elements: dict
        description: |
          List of dictionaries passed as arguments to
          kubernetes.core.helm_repository.
        default: []
        options:
          name:
            type: str
            required: true
          password:
            type: str
          username:
            type: str
          url:
            type: str

      auths:
        type: list
        elements: dict
        description: |
          List of dictionaries passed as arguments to
          kubernetes.core.helm_registry_auth.
        default: []
        options:
          state:
            description:
              - Desired state of the registry.
              - If set to V(present) attempt to log in to the remote registry server using the URL specified in O(host).
              - If set to V(absent) attempt to log out from the remote registry server using the URL specified in O(host).
            default: present
            choices: ['present', 'absent']
            type: str
          host:
            description: Provide a URL for accessing the registry.
            required: true
            type: str
          insecure:
            description:
              - Allow connections to SSL sites without certs.
            default: false
            type: bool
          username:
            type: str
          password:
            type: str

      release_common_opts:
        type: dict
        description: |
          Common arguments for every helm invocation.
        default: {}
        options:
          create_namespace:
            type: bool
            default: true
          chart_repo_url:
            type: str
          disable_hook:
            type: bool
          history_max:
            type: int
          purge:
            type: bool
          replace:
            type: bool
          skip_crds:
            type: bool
          wait:
            type: bool
            default: true
          wait_timeout:
            type: str
            default: "5m"
          atomic:
            type: bool
            default: true
